### ISSUE TITLE
nuget

### ISSUE THREAD

**Issue by chunkychode** [simonpinn/Neo4jClient.Extension#17]
can you make the nuget version include Pullrequest #11 
such an awesome feature :)

**Comment by neutmute** [comment]
fyi - i have myget generating builds off my develop branch which you can grab here in the interim
https://www.myget.org/F/neo4jclient-extension-tx/api/v2

**Comment by chunkychode** [comment]
perfect.  thank you.

**Comment by simonpinn** [comment]
Hey guys,
Latest build is up and pushed to nugget, sorry for taking a bit of time getting it up.
cheers

**Comment by neutmute** [comment]
awesome - thanks

**Comment by neutmute** [comment]
voting to close
