### ISSUE TITLE
Effectively using MergeRelationship to perform relationship upserts

### ISSUE THREAD

**Issue by rajivkukreja** [simonpinn/Neo4jClient.Extension#19]
Greetings -

Thank you for this awesome piece of work. I am however struggling to understand how best to use MergeRelationship. The examples in the unit tests as well as the docs are a bit scant.

The general approach I am taking is to first independently merging all nodes (from a master datasource) followed by independently merging all relationships amongst these nodes (from a master datasource). This is to ensure that all nodes pre-exist before the relationships are attempted.

My current use is generating the following **invalid** cypher...
```
MERGE (NameOfCompany)-[NameOfRelationship:Link]->(NameOfPerson)
ON MATCH SET NameOfRelationship.Citations = [
  "575f2aae93e9eb097022ccac",
  "575f2aae93e9eb097022ccad"
]
ON MATCH SET NameOfRelationship.Value = null
ON MATCH SET NameOfRelationship.Id = "575f2aae93e9eb097022ccc6"
ON MATCH SET NameOfRelationship.To = "NameOfPerson"
ON MATCH SET NameOfRelationship.Type = "NameOfRelationship"
ON MATCH SET NameOfRelationship.From = "NameOfCompany"
ON CREATE SET NameOfRelationship = {
  Citations: [
    "575f2aae93e9eb097022ccac",
    "575f2aae93e9eb097022ccad"
  ],
  Value: null,
  Id: "575f2aae93e9eb097022ccc6",
  To: "NameOfPerson",
  Type: "NameOfRelationship",
  From: "NameOfCompany"
}
```

I have tried using FluentConfig as follows:

```C#
var ctx = new CypherExtensionContext();
ctx.JsonContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver();
FluentConfig.Config(ctx)
                        .With<Link>()
                        .Match(x => x.From)
                        .Match(x => x.Type)
                        .Match(x => x.To)
                        .MergeOnMatchOrCreate(x => x.From)
                        .MergeOnMatchOrCreate(x => x.Type)
                        .MergeOnMatchOrCreate(x => x.To)
                        .MergeOnMatchOrCreate(x => x.Id)
                        .MergeOnMatchOrCreate(x => x.Value)
                        .MergeOnMatchOrCreate(x => x.Citations)
                        .Set();
```
And the Link class looks like this:

```C#
public class Link : Edge
{
        public string Id { get; set; }

        public string From { get; set; }

        public string Type { get; set; }

        public string Value { get; set; }

        public string To { get; set; }

        public string[] Citations { get; set; }

        public Link(Data.Link link) : base(link.RelationName, link.FromName, link.ToName)
        {
            Id = link.Id.ToString();
            From = link.FromName;
            Type = link.RelationName;
            To = link.ToName;
            Value = link.Qualifier;
            Citations = link.Citations.Select(x => x.ToString()).ToArray();
        }
}

public class Edge : BaseRelationship
{
        public Edge(string rel, string from, string to) : base(rel.ToUpper().Replace(" ","_"), from, to)
        {
        }
}
```

And the actual use of MergeRelationship looks as follows:
```C#
try
{
      Graph.Configure(); // this does the FluentConfig shown above
       var query = new CypherFluentQuery(_client); // _client is an instance of GraphClient
       query = query.MergeRelationship<Link>(element as Link) as CypherFluentQuery;
       Console.WriteLine(query.GetFormattedDebugText()); // this spits out the Cypher shown above
       query.ExecuteWithoutResults();
}
catch (Exception ex)
{
       Console.WriteLine("Failed to upsert because {0}", ex.GetBaseException().Message);
}
```

which catches the exception with the following error message:

Invalid input 'N': expected whitespace, comment, node labels, MapLiteral, a parameter, ')' or a relationship pattern (line 1, column 25 (offset: 24))
"MERGE (NameOfCompany)-[NameOfRelationship:Link]->(NameOfPerson)
"

Note that in the above highlighted issue - I have replaced the real name of the company, person and relationship with **NameOfCompany**, **NameOfPerson** and **NameOfRelationship** respectively.

The correct / **valid** cypher I am trying to get to is as follows:
```

MATCH (n {Name:"NameOfCompany"}),(m {Name:"NameOfPerson"})
MERGE (n)-[r:RELATIONSHIP_KEY {Type:"NameOfRelationship"}]->(m)
ON MATCH SET r.Citations = [
  "575f2aae93e9eb097022ccac",
  "575f2aae93e9eb097022ccad"
]
ON MATCH SET r.Value = null
ON MATCH SET r.Id = "575f2aae93e9eb097022ccc6"
ON MATCH SET r.To = "NameOfPerson"
ON MATCH SET r.Type = "NameOfRelationship"
ON MATCH SET r.From = "NameOfCompany"
ON CREATE SET r = {
  Citations: [
    "575f2aae93e9eb097022ccac",
    "575f2aae93e9eb097022ccad"
  ],
  Value: null,
  Id: "575f2aae93e9eb097022ccc6",
  To: "NameOfPerson",
  Type: "NameOfRelationship",
  From: "NameOfCompany"
}
```

Any help in understanding the proper way to describe the FluentConfig would be greatly appreciated.

Thanks very much!

**Comment by neutmute** [comment]
Hi Rajiv 
See [this example](https://github.com/simonpinn/Neo4jClient.Extension/blob/master/test/Neo4jClient.Extension.UnitTest/Cypher/FluentConfigMergeTests.cs#L121) which you can execute from both an integration test and a unit test.

Your problem is you are expecting the `MergeRelationship` to work in isolation, but what you need to do is first to have *matched or merged* your two nodes and have have given those two nodes identifiers from which the `from` and `to` can be used to link.

The identifiers are a little bit magical - in that they are using the default identifiers for that entity...
`
var q = GetFluentQuery()
             .MergeEntity(testPerson)
             .MergeEntity(testPerson.HomeAddress)
             .MergeRelationship(homeAddressRelationship);
`

, but each of the `MergeEntity` / `MatchEntity` methods provide overloads to let you supply custom identifiers

Your fluent config should look more like this  - with the `from` and `to` fields removed

```
FluentConfig.Config(ctx)
                        .With<Link>()
                        .Match(x => x.Type)
                        .MergeOnMatchOrCreate(x => x.Type)
                        .MergeOnMatchOrCreate(x => x.Id)
                        .MergeOnMatchOrCreate(x => x.Value)
                        .MergeOnMatchOrCreate(x => x.Citations)
                        .Set();
```

Does that help?

**Comment by simonpinn** [comment]
Thanks neutmute, you beat me to it.

Sent from my HTC on the Telstra Mobile network

----- Reply message -----

**Comment by rajivkukreja** [comment]
Thank you @neutmute and @simonpinn! Yes - thats very helpful. @neutmute - on your very last statement about `From` and `To` needing to be identifiers of the nodes previously matched using MatchEntity<T> - a couple of follow ups:

a) Given that the actual node identifiers themselves are volatile in Neo4j, I am using the `Name` property for uniqueness of a node. By **Identifiers**, are you referring to the volatile NodeReference Ids or the domain specific unique identifiers i.e. `Name` in my case? I am using the latter to populate `From` and `To` at the moment.
b) And somewhat related depending on the answer to a) - If those `From` and `To` are meant to be NodeReference Ids - then does that happen implicitly/automagically if a MergeRelationship is chained after a couple of MatchEntity calls?

Thanks again!
Rajiv

**Comment by simonpinn** [comment]
Hi Rajiv,


The identifier is the key you define for a given Match/Merge statement, this by default is generated by the entity, as pointed out, but you can provide your own, which I would recommend, I usually use an entity.Id.

For example:

var query = _graphClient.Cypher

.MergeEntity(person1, "John")

.MergeEntity(person2, "Jane")

.MergeRelationship(new Knows("John", "Jane"));


Where Knows is a class derived from BaseRelationship and the "from" and "to" are constructor args. "John" and "Jane" are query identifiers, like using AS in SQL, and allow you to reference a particular node while composing a query, in practice I would use person1.Id.


So, no, the identifier is not the volatile Neo4j id, just a reference for the query.


Hope that helps,


cheers


Simon


________________________________

**Comment by neutmute** [comment]
[This pdf](http://neo4j.com/docs/pdf/neo4j-cypher-refcard-stable.pdf) is the nearest I can find to an official explanation of `identifier`

They may have changed their terminology since in [6.3 of these docs](http://neo4j.com/docs/developer-manual/current/#query-syntax) they appear to be calling them variables now (I'm sure they were called identifiers before as I specifically went and looked it up).

Where I used the term `identifier` above - they are for example the `n`, `r`, `m` variables below
`CREATE(n)-[r:KNOWS]->(m)`

Variables probably makes more sense from a naming point of view

**Comment by simonpinn** [comment]
True - variables is probably the best name

________________________________

**Comment by neutmute** [comment]
I'm not going mad - [this post ](http://wes.skeweredrook.com/cypher-matching-traversal-patterns-with-match/)uses the terms `bound identifier` and `unbound identifier`

> First, you need to understand the difference between bound and unbound identifiers (sometimes we call them variables, too, in case I slip up and forget to be consistent). 

but docs are definitely [now calling them variables](http://neo4j.com/developer/cypher-query-language/)

**Comment by rajivkukreja** [comment]
Thank you @simonpinn  and @neutmute !
I was indeed interpretting **identifiers** incorrectly. Yes - calling them **variables** makes far more sense.

Thanks again
