### ISSUE TITLE
Question - Merge/Create (upsert)

### ISSUE THREAD

**Issue by TLogik** [simonpinn/Neo4jClient.Extension#20]
Hi.
Just started using Neo4J and found your nice extensions to the C# client. 👍 
I do have a question that i am not able to extrapolate from code or tests.

Is it possible to create Upserts? Merge/Create via your library? and if so how?

Kindly
Thomas

**Comment by simonpinn** [comment]
Hi Thomas,

Great to hear from you, and yes, that is exactly why using the library can save so much time. Upserts are achieved by using ```Merge``` fluent config and optionally the  ```MergeOnMatchOrCreate```/```MergeOnMatch```/```MergeOnCreate``` or equivalent attributes ```CypherMerge``` and optionally the```CypherMergeOnMatch```/```CypherMergeOnCreate```.
These will control when the property participates in the MERGE and ON CREATE/MATCH statements. 
https://github.com/simonpinn/Neo4jClient.Extension/blob/master/test/Neo4jClient.Extension.UnitTest/Cypher/FluentConfigMergeTests.cs#L73 is a good example of it all running together.

Let me know if you need a more succinct example, happy to send you a gist.

cheers

Simon

**Comment by TLogik** [comment]
Hi Simon.
I had missed that in the test - but it makes sense.
I have now tested the setup and i have some issues. Properly because  i am a NEO4J newb.
My update/Create does not work as expected.

See my setup below.

CONFIG
``` csharp
public static Unit Init(IGraphClient client)
        {
            client.Connect();
            FluentConfig.Config()
                .With<Person>()
                .Match(p => p.Name)
                .MergeOnCreate(p => p.Name)
                .MergeOnCreate(p => p.CreatedAt)
                .MergeOnMatchOrCreate(p => p.FavoriteFood)
                .Set();

            FluentConfig.Config()
                .With<Vehicle>()
                .Match(p => p.Id)
                .MergeOnCreate(p => p.Id)
                .MergeOnCreate(p => p.Purchased)
                .MergeOnMatchOrCreate(p => p.Make)
                .MergeOnMatchOrCreate(p => p.Model)
                .Set();

            FluentConfig.Config()
                .With<LoveRelation>()
                .Set();


            FluentConfig.Config()
                .With<HateRelation>()
                .Set();

            FluentConfig.Config()
                .With<OwnsRelation>()
                .Set();


            FluentConfig.Config()
                .With<DrivesRelation>()
                .Match(r => r.Effective)
                .MergeOnMatchOrCreate(r => r.Effective)
                .Set();
            return Unit.Default;
        }
```

Update create code
```csharp
 public Unit UpdateModel(IGraphClientFactory factory)
        {
            var tom = new Person
            {
                Name = "Tommy",
                CreatedAt = DateTimeOffset.Now,
                FavoriteFood = "Banana"
            };

            var johnny = new Person
            {
                Name = "Johnny",
                CreatedAt = DateTimeOffset.Now,
                FavoriteFood = "Game Foul"
            };

            using (var client = factory.Create())
            {
                var q = client.Cypher
                    .MergeEntity(tom);
                q.ExecuteWithoutResults();


                q = client.Cypher
                    .MergeEntity(johnny);
                q.ExecuteWithoutResults();

                johnny.FavoriteFood = "Soup";
                q = client.Cypher
                    .MergeEntity(johnny);
                q.ExecuteWithoutResults();

            }
            return Unit.Default;
        }
```

Expectation.
I have a breakpoint on each execute of the query and here is what i expect.
1. Person Tom is created. It happens
1. Person Johnny is created. It is not. Person Toms favorite food is updated to Game Foul.
1. Person Johhnys food is updated. It is not. Toms favorite food is updated to Soup

I cannot understand how that is so since i am configuring the system to match on Name and the names of the two persons are very different.

Maybe i am missing the obvious but i dont get it.
I hope you have a bit of insight here.

**Comment by TLogik** [comment]
Hi.
So i made this smal change to my config
```csharp
 FluentConfig.Config()
                .With<Person>()
                .Match(p => p.Name)
                .Merge(p => p.Name)
                .MergeOnCreate(p => p.Name)
                .MergeOnCreate(p => p.CreatedAt)
                .MergeOnMatchOrCreate(p => p.FavoriteFood)
                .Set();

            FluentConfig.Config()
                .With<Vehicle>()
                .Match(p => p.Id)
                .Merge(p => p.Id)
                .MergeOnCreate(p => p.Id)
                .MergeOnCreate(p => p.Purchased)
                .MergeOnMatchOrCreate(p => p.Make)
                .MergeOnMatchOrCreate(p => p.Model)
                .MergeOnMatchOrCreate(p => p.Name)
                .Set();
```
note the use of ```Merge(p => p.Name)``` on person and also on Vehicle. That did the trick and entities are correctly matched on merge and created if not existing.
Could you please explain why it now works after the addition of the merge clause.
Kindly
Thomas

**Comment by simonpinn** [comment]
Hi Thomas,

To understand the why it is best to take a look at the CQL that is produced by the library.
*Without* the ```Merge(p => p.Name)``` the CQL produced is:
```
MERGE (person:Person)
ON MATCH
SET person.favoriteFood = "Banana"
ON CREATE
SET person = {
  "favoriteFood": "Banana",
  "createdAt": "2017-01-31T08:56:53.1542167+11:00",
  "name": "Tommy"
}
--------------
MERGE (person:Person)
ON MATCH
SET person.favoriteFood = "Game Foul"
ON CREATE
SET person = {
  "favoriteFood": "Game Foul",
  "createdAt": "2017-01-31T08:56:53.1542167+11:00",
  "name": "Johnny"
}
```
Note the first line in each statement, is just:
```MERGE (person:Person)```
There are no other node attributes to merge on.

Now *with* the ```Merge(p => p.Name)```:
```
MERGE (person:Person {name:{
  "name": "Tommy"
}.name})
ON MATCH
SET person.favoriteFood = "Banana"
ON CREATE
SET person = {
  "favoriteFood": "Banana",
  "createdAt": "2017-01-31T09:05:42.8719166+11:00",
  "name": "Tommy"
}
--------------
MERGE (person:Person {name:{
  "name": "Johnny"
}.name})
ON MATCH
SET person.favoriteFood = "Game Foul"
ON CREATE
SET person = {
  "favoriteFood": "Game Foul",
  "createdAt": "2017-01-31T09:05:42.8719166+11:00",
  "name": "Johnny"
}
```
You'll note the CQL ```Merge``` statements now include the property Name.
The ```Merge(p => p.Name)``` controls properties which participate in ```client.Cyphet..MergeEntity(X)``` while 
```Match(p => p.Name)``` controls properties which participate in ```client.Cyphet..MatchEntity(X)```

You can view the CQL by querying ```q.Query.DebugQueryText``` for example:
```
q = client.Cypher
                .MergeEntity(johnny);
            Console.WriteLine(q.Query.DebugQueryText);
            q.ExecuteWithoutResults();
```
This will print the CQL.

Hope that helps, the library enables you to write strongly typed CQL from classes, it does require a little bit of thought as to how that translates to CQL, just like a ORM to SQL does.

Ok to close?

cheers

Simon

**Comment by TLogik** [comment]
Thanks for the indepth explanation 👍 
I will fork the repo and best as possible over time add documentation.
I will close the question as resolved.

**Comment by simonpinn** [comment]
No problem Thomas, let me know if you get stuck.

cheers

**Comment by neutmute** [comment]
Just to chip in - I've built two production apps with this library now - so it should do everything you need. the trick is just working out how :)
