### ISSUE TITLE
Question. How to get all nodes of type?

### ISSUE THREAD

**Issue by TLogik** [simonpinn/Neo4jClient.Extension#21]
Hi again. Taking you up on the offer about a bit of help :)

If i have an entity and in the config i have setup a Match clause.
```
 FluentConfig.Config()
                .With<FbComment>()
                .Match(p => p.EntityId)
                .Merge(p => p.EntityId)
                .MergeOnCreate(p => p.CreatedAt)
                .MergeOnMatchOrCreate(p => p.UpdatedAt)
                .MergeOnMatchOrCreate(p => p.Url)
                .MergeOnMatchOrCreate(p => p.IndexedAt)
                .MergeOnMatchOrCreate(p => p.Message)
                .MergeOnMatchOrCreate(p => p.Hashtags)
                .Set();
```
It is not possible to make a query that hits all the nodes like the below
```csharp
 using (var client = GraphClientFactory.Create())
            {
                var q = client.Cypher
                    .MatchEntity(new FbComment(), "c")
                    .Return(c=> c.As<FbComment>())
                    .Limit(10);
                var pages = q.Results.ToList();
            }
```

Cypher query
```
MATCH (c:FbComment {entityId:{
  "entityId": null
}.entityId})
RETURN c
LIMIT 10
```

because the query will state that  it needs to match the entityId and no node has an entityId of null.

If i remove the Match statement from the config i get results back.

Is there a way around this since i would like to have the match in the config for many other operations?

Thanks

**Comment by simonpinn** [comment]
Hi Thomas,

No problem, first off you should avoid getting all nodes, but if you do need to do it, then it is no problem at all, and really the extension library doesn't need to be used, but if you do want to use it then you would do the following:
```             var q = client.Cypher
                    .MatchEntity(new FbComment(), "c", propertyOverride: new List<CypherProperty>())
                    .Return(c=> c.As<FbComment>())
                    .Limit(10);
                var pages = q.Results.ToList();
```
Note the addition of ```propertyOverride: new List<CypherProperty>()``` you can think of the fluentconfig as the default, since generally you would use the library to find a node as a starting point for a query. This syntax allows you to specify the properties that will participate in the ```Match```. There is also a helper extension, but it is currently an internal method https://github.com/simonpinn/Neo4jClient.Extension/blob/f71c337ea668eefe8e8f4990c51ebec977bf4079/src/Neo4jClient.Extension/Cypher/Extension/CypherExtension.Entity.cs#L51 which I might make public.

The other way is just a plan CQL statement 
```             var q = client.Cypher
                    .Match("MATCH (c:FbComment) RETURN c")
                    .Return(c=> c.As<FbComment>())
                    .Limit(10);
                var pages = q.Results.ToList();        
```
To answer the next question about casing, the base Neo4jClient library does have a little quirk, in that you need to set the ```CamelCasePropertyNamesContractResolver``` which you do like so:
```
            var client = new GraphClient(new Uri("http://localhost:7474/db/data"),"xxx", "xxx")
            {
                JsonContractResolver = new CamelCasePropertyNamesContractResolver()
            };
            client.Connect();
```

Hope that helps,

cheers

Simon

**Comment by TLogik** [comment]
> No problem, first off you should avoid getting all nodes, but if you do need to do it, then it is no problem at all, and really the extension library doesn't need to be used, but if you do want to use it then you would do the following:

I Was actually using the Limit to reduce results but removed it to keep the example clean :-) But you are of course right. You normally do not want to stream all nodes out unless you really, really need to.

So all your suggestions work 👍 👍  Awesome. You saved me so much time. Thanks.

So now i have just a tiny little question :)
In the query below i get the full object back, but all i really need is the value of post.UpdatedAt
```
                var q = client.Cypher
                    .MatchEntity(new FbPost(), "post", propertyOverride: new List<CypherProperty>())
                    .Return(post => post.As<FbPost>())
                    .OrderByDescending("post.UpdatedAt")
                    .Limit(10);
```
is it possible to specify how it should return, rather than specifying that it should be serilaized into a full object. It can of couse be done i CQL but is it also possible using a more strongly typed approach?

Thanks again for all the awesome help. It is much appreciated.

Regards
Thomas

**Comment by simonpinn** [comment]
Hi Thomas,

Great to hear that solved your main issues. As far as returning a cut down model I would consider either using a CQL query ie ```MATCH (x:FbPost) RETURN x.UpdatedAt``` or to use the library, then you would use a class that has just that property, with a config which sets the cypher node label to the same as the full enity, ie; if FbPost then ```.With<FbPostDateOnly>("FbPost")```

Then you would just query as:
```
 var q = client.Cypher
                    .MatchEntity(new FbPostDateOnly(), "post", propertyOverride: new List<CypherProperty>())
                    .Return(post => post.As<FbPostDateOnly>());
```

Let me know if that is clear.

cheers

Simon

**Comment by TLogik** [comment]
Great thanks. 
That clears it up quite a bit and things are working nicely.
But as i use the lib other questions pop up.
To make it clear when using the lib i will ask them as separate questions.
cheers
Thomas
