### ISSUE TITLE
Question. Rehydrating a node does not yield any data

### ISSUE THREAD

**Issue by TLogik** [simonpinn/Neo4jClient.Extension#22]
I have a problem and would like to check up that i am not doing something wrong before i think of this as an issue.

Consider this object.
```csharp
public class Country
    {
        public string Code { get; set; }
        public string Name { get; set; }
}
```

When inserting this object into the database the object looks like this.
```
code	DK
name	Denmark
```

If i try and rehydrate this object in code>
```csharp
            using (var client = GraphClientFactory.Create())
            {
                var q = client.Cypher
                    .Country(), "c").Return(c => c.As<Country>());
                var res = q.Results.ToList();
            }
```
i get a number of objects back but they are not containing any data. I.e. no hydration.

If i modify the object to look like this.

```csharp
    public class Country
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string code { get; set; }
        public string name { get; set; }
}
```
then *name* and *code* are hydrated.

So my question is.
If the client takes my Pascal Case properties and inserts them as Camel Case, then how can it be that rehydrating the object the Client cannot figure out the reverse, i.e. taking Camel Case properties from DB and setting the Pascal Case properties of the object.

Maybe i have to make some changes but it seems wierd if i have to Camel case all my C# properties and that is not what i see in the test of this solution.

All help is appreciated highly.
Kindly
Thomas
btw for clarity.
Camel Case = Lower Camel Case => camelCase
Pascal Case = Upper Camel Case => Camel Case

**Comment by simonpinn** [comment]
Hi Thomas,

See https://github.com/simonpinn/Neo4jClient.Extension/issues/21 you'll need to set the underlying Neo4JClient ```JsonContractResolver = new CamelCasePropertyNamesContractResolver()```

thanks

Simon

**Comment by TLogik** [comment]
Hi Simon.
Thanks very much.
I have commented in post #21 where stating that you have provided the solution for all my current questions 👍 

I am closing this question
Thanks.
Thomas
