### ISSUE TITLE
Is this project still supported? I wanted to use it for a .NET core 2.0 project.

### ISSUE THREAD

**Issue by ddeamaral** [simonpinn/Neo4jClient.Extension#29]
Hi, I haven't seen a commit in almost a year with this package. Is it still being actively developed/taken care of, or has this project been abandoned? Also, is there any documentation anywhere?

Thanks.

**Comment by neutmute** [comment]
Hey - docs are limited to the readme.md and unit tests.
I moved on from the company where it was being used but it was battle tested in production. Should be fine with some package updates to latest Neo4jClient.
