### ISSUE TITLE
Possible to use in a Portable Class Library

### ISSUE THREAD

**Issue by ravensorb** [simonpinn/Neo4jClient.Extension#4]
Question -- is there any recommended way to use the attributes in a Portable Class Library?

**Comment by simonpinn** [comment]
Hi Shawn,

The question would more be whether the Neo4jClient library itself can be used in a PCL, which I’m not certain of, a quick look suggests not, https://github.com/Readify/Neo4jClient/issues/45

As for the extension attributes, I don’t see why not, I’d definitely recommend using the fluent config, so you could use them unobtrusively. That way you don’t need to use the attributes, just use any class, PCL or not.

Cheers

Simon

**Comment by simonpinn** [comment]
Closing due to lack of support in Neo4jClient
